### ISSUE TITLE
Support .Net Framework

### ISSUE THREAD

**Issue by sergiorykov** [tsolarin/readline#10]
You can't install nuget package for .Net Framework, unless you will explicitly specify it.

![image](https://cloud.githubusercontent.com/assets/292285/23093619/56388b4a-f5f9-11e6-91e9-55d758ea46d8.png)

**Comment by tonerdo** [comment]
@sergiorykov this is expected as .NET Framework 4.5.2 doesn't support `netstandard1.3`. Although from the looks of things it seems adding `net45` to the list of frameworks in the `project.json` should do the trick (although I don't currently have access to a Windows machine so I can't verify this).
Is it possible you clone this repo and try it out? If it works I look forward to a PR :)

**Comment by tonerdo** [comment]
Fixed in #11
