### ISSUE TITLE
net standard compatibility

### ISSUE THREAD

**Issue by Poltuu** [tsolarin/readline#2]
Hi,

I'm trying to use this library that looks very promising. Unfortunately, my projects use .Net framework 4.6.1, which is not compatible netstandard1.3.

Do you believe it would be possible to increase the compatibility of the library by changing the required framework ?

**Comment by tonerdo** [comment]
@Poltuu from the compatibility table here (https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) you can see that .Net framework 4.6.1 supports netstandard1.3. Are you having troubles requiring from NuGet?

**Comment by Poltuu** [comment]
Mmm, I guess so then.
Nuget tells me : 
'ReadLine' could not be installed because it is not compatible with any project in the solution.

Maybe that's because my nuget version is too old? I'm using VS2013

**Comment by Poltuu** [comment]
thanks, that was it :)
