### ISSUE TITLE
It doesn't install correctly

### ISSUE THREAD

**Issue by pietklop** [tsolarin/readline#21]
I tried to install it using nuget in visual studio enterprise 2017 in a 4.6 console application. It seems to install but i won't get any references added? Have the same result in vs 2015.

**Comment by tonerdo** [comment]
@pietklop I assume you're trying to import it as a namespace `using`. You don't need to, as long as you have `using System;` you should be able to just call `ReadLine.Read()` anywhere in the code file

**Comment by pietklop** [comment]
thx for your fast reply. I downloaded and imported the code manually and it works fine :) But i couldn't make it work using nuget like i mentioned before.

**Comment by waf** [comment]
I'm seeing this issue. I've verified that I have `using System;` in my file. Like pietklop, I'm using .NET 4.6 (specifically, 4.6.1).

Here's a verbose log 

```
PM> Install-Package ReadLine -verbose
  GET https://api.nuget.org/v3/registration1-gz/readline/index.json
  OK https://api.nuget.org/v3/registration1-gz/readline/index.json 1119ms


Attempting to gather dependency information for package 'ReadLine.1.1.0' with respect to project 'Donatello', targeting '.NETFramework,Version=v4.6.1'
Package ReadLine from source api.nuget.org gathered from cache.
Total number of results gathered : 50
Gathering dependency information took 63.45 ms
Summary of time taken to gather dependencies per source :
Attempting to resolve dependencies for package 'ReadLine.1.1.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'ReadLine.1.1.0'
Resolved actions to install package 'ReadLine.1.1.0'
Retrieving package 'ReadLine 1.1.0' from 'api.nuget.org'.
Adding package 'ReadLine.1.1.0', which only has dependencies, to project 'Donatello'.
Adding package 'ReadLine.1.1.0' to folder 'C:\Users\waf\Documents\Visual Studio 2015\Projects\Donatello\packages'
Added package 'ReadLine.1.1.0' to folder 'C:\Users\waf\Documents\Visual Studio 2015\Projects\Donatello\packages'
Added package 'ReadLine.1.1.0' to folder 'C:\Users\waf\Documents\Visual Studio 2015\Projects\Donatello\packages' from source 'https://api.nuget.org/v3/index.json'
Added package 'ReadLine.1.1.0' to 'packages.config'
Successfully installed 'ReadLine 1.1.0' to Donatello
Added file 'app.config'.
Executing nuget actions took 546.09 ms
Time Elapsed: 00:00:01.8111730
```

The "which only has dependencies" part looks a bit suspicious.

**Edit**: Some more information: If I go to my solution's `packages\ReadLine.1.1.0` directory, there are no DLLs in it, just a `ReadLine.1.1.0.nupkg` file. If I look inside the nupkg, there is some metadata, but no DLLs.

**Comment by tsolarin** [comment]
@waf thanks for this, I think I found the issue. I'll release a recovery package version today

**Comment by tonerdo** [comment]
@waf @pietklop I've released a new patch that should fix it: https://www.nuget.org/packages/ReadLine/1.1.1

**Comment by waf** [comment]
@tsolarin Version 1.1.1 installs perfectly. Thanks!
