### ISSUE TITLE
Smart auto prompting option

### ISSUE THREAD

**Issue by Astaelan** [tsolarin/readline#47]
Provide option to enable and configuration, disabled by default for normal behavior.

When enabled, would proxy output by redirecting Console.Out stream, and inject a prompt after a configurable grace period (default 10ms?) by starting a delayed task that is cancelled and restarted when new output occurs and the last characters are a newline, which would prevent it from trying to inject a prompt when already sitting at a prompt.

This would be a significant improvement over how traditional readline works by not injecting prompts in the middle of busy output, and will in fact ensure a prompt is provided when output becomes sufficiently idle.

**Comment by Latency** [comment]
This is not a feature of the API.. this is a mechanic of how 'Console' behaves in general... particularly, STDOUT which is different than STDIN.  

For example,
```CSSharp
static void Main(string[] args)
{
    StreamWriter writer = new StreamWriter("Output.txt");
    Console.SetOut(writer);
    Console.Out.WriteLine("Out"); // stored in output.txt    
    Console.Error.WriteLine("Error"); // written to screen    
    Console.WriteLine("Default");    
    writer.Dispose(); 
}
```

Assemblies:
System.Console.dll, mscorlib.dll, netstandard.dll


Hence, I would imagine that you could implement a derived class which handles what you want it to do.

**Comment by Astaelan** [comment]
Author isn't interested.
