### ISSUE TITLE
Ctrl+C: doesn't work on Windows

### ISSUE THREAD

**Issue by gitchomik** [tsolarin/readline#5]
Ctrl+C: doesn't work on Windows .NET Core
Ctrl+C: doesn't work on Windows .NET
Ctrl+C: work on Linux .NET Core

**Comment by tonerdo** [comment]
I don't have a Windows right now to test this on. So while I'm working on getting one, anyone is free to help out with this

**Comment by gitchomik** [comment]
@tsolarin : I figured out, that it is not bug in your code.
The problem appears only when **I attach to process** (using VS.NET 2013). When I starting app directly from IDE the problem **not occurs**. It seems that attaching VS.NET 2013 debbuger to running app, causes problem with handling [Ctrl] +[C] (on Console.ReadKey). Maybe it is a VS.NET 2013 bug ?

Any way I think that issue can be closed. 
Can anybody confirm that problem on other VS.NET versions ?
