### ISSUE TITLE
Is this repo still alive?

### ISSUE THREAD

**Issue by WojciechNagorski** [tsolarin/readline#56]
The last version of Readline was published 12.06.2018. There are great PRs, but I don't see responses.
Is this repo still alive?

**Comment by Latency** [comment]
It is very much alive.  Although,  I have been away for the past few months, holidays, etc.

What are you needing addressed?

**Comment by drewburlingame** [comment]
Hi @Latency.  I would find the following PRs useful:  #57, #51, #38 & #27.  Also all updates from https://github.com/rubberduck203/readline/ including the PR I just submitted to them (https://github.com/rubberduck203/readline/pull/2)

Do you think you'd be able to review them in the near future?

**Comment by rubberduck203** [comment]
I wouldn’t recommend merging my fork in as is. While it does offer a huge experience improvement in the way it rewrites entire lines instead of character by character, there is a bug around some edge cases involving line length.

**Comment by drewburlingame** [comment]
@Latency should I submit PRs to this repo or your fork?

**Comment by WojciechNagorski** [comment]
It looks like it's dead.
