### ISSUE TITLE
[Feature request] : AutoComplete forward/backward

### ISSUE THREAD

**Issue by gitchomik** [tsolarin/readline#6]
Please add backward completion with [Shift]
[Shift] + [Tab] : Command line (backward) completion 
[Tab] : Command line (forward) completion

**Comment by tonerdo** [comment]
@gitchomik in what situation will a user want this feature?

**Comment by gitchomik** [comment]
@tsolarin If you have a lot of element, and you miss one, it is easy way back to the previous. Windows "cmd" has this feature.

**Comment by tsolarin** [comment]
Resolved by #12 
/cc @gitchomik

**Comment by tonerdo** [comment]
Resolved by #12
/cc @gitchomik
